### PR TITLE
Create server-has-ssl3-fallback-enabled.md

### PR DESCRIPTION
**Pull request by skibz**
possible duplicate of `disable-sslv3`?

### CODE REVIEW

**Comment by Johanndutoit** [comment]
Not quite. SSL can have the fallback enabled, which will allow some versions of OpenSSH to fallback from TLS. See http://disablessl3.com/.

```
A possible mitigation, to be implemented on both the server and the client, is to add support for the TLS Fallback Signaling Cipher Suite Value (TLS_FALLBACK_SCSV). This new feature prevents protocol downgrade attacks when certain applications such as web browsers attempt to reconnect using a lower protocol version. It also prevents downgrades from TLS 1.2 to 1.1 or 1.0 and so may help prevent future attacks. You will get this patch in your regular software updates, but it is not enough, since it will work only if both sides of the connection have been patched.
```

**Comment by Johanndutoit** [comment]
Ping :)

**Comment by skibz** [comment]
i've been researching this further. it seems the solution is to simply disable ssl3 for the server in question?

**Comment by Johanndutoit** [comment]
Mergin for now, as it contains the needed information.

**Pull request merged**
