### PR TITLE
add safe-browsing-reported-link-to-page-on-same-domain-hosts-phishing…

### PR DESCRIPTION
**Pull request by garethnic**

### CODE REVIEW

**Comment by Johanndutoit** [comment]
Nice, do me a quick favour and add some context that this was brought up as a issue for urls on your website itself.

We check for three things. Urls flagged on external sites, urls flagged on your site you are linking to and if the page itself is flagged.

**Comment by garethnic** [comment]
On it

**Comment by garethnic** [comment]
Updated

**Comment by Johanndutoit** [comment]
LGTM, thanks

**Pull request merged**
